# Licensed under the Apache-2.0 license

[package]
name = "emulator-cbinding-minimal"
version = "0.1.0"
edition = "2021"

[lib]
name = "emulator_cbinding_minimal"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc.workspace = true
